# ============================================================================
# BACKEND CONFIGURATION - Development Environment
# ============================================================================
# 
# This file is auto-generated by the backend module
# Replace the placeholder values with actual outputs from:
#   cd backend && terraform apply
#
# Remote state is managed in S3 with DynamoDB locking
# Each environment has its own state file in the same bucket
#
# ============================================================================

terraform {
  backend "s3" {
    # These values are replaced by outputs from backend/main.tf
    bucket         = "REPLACE_WITH_BACKEND_S3_BUCKET_NAME"
    key            = "stage/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "REPLACE_WITH_DYNAMODB_TABLE_NAME"
    encrypt        = true
    kms_key_id     = "REPLACE_WITH_KMS_KEY_ARN"
  }
}

# ============================================================================
# MANUAL SETUP INSTRUCTIONS
# ============================================================================
# 
# 1. Deploy backend first:
#    cd backend
#    terraform apply
#    terraform output backend_config
#
# 2. Copy the output and update this file with the values
#
# 3. Then initialize this environment:
#    cd environments/dev
#    terraform init
#
# ============================================================================
